// Project-related constants

// Tech icon mapping with Simple Icons (real logos) and colors
export const TECH_ICONS = {
    react: { slug: "react", color: "text-cyan-400", bg: "bg-cyan-500/10" },
    reactjs: { slug: "react", color: "text-cyan-400", bg: "bg-cyan-500/10" },
    "react native": { slug: "react", color: "text-cyan-400", bg: "bg-cyan-500/10" },
    angular: { slug: "angular", color: "text-red-400", bg: "bg-red-500/10" },
    ionic: { slug: "ionic", color: "text-blue-400", bg: "bg-blue-500/10" },
    "ionic capacitor": { slug: "capacitor", color: "text-blue-400", bg: "bg-blue-500/10" },
    capacitor: { slug: "capacitor", color: "text-blue-400", bg: "bg-blue-500/10" },
    flutter: { slug: "flutter", color: "text-sky-400", bg: "bg-sky-500/10" },
    "node.js": { slug: "nodedotjs", color: "text-green-400", bg: "bg-green-500/10" },
    nodejs: { slug: "nodedotjs", color: "text-green-400", bg: "bg-green-500/10" },
    express: { slug: "express", color: "text-zinc-400", bg: "bg-zinc-500/10" },
    mongodb: { slug: "mongodb", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    mysql: { slug: "mysql", color: "text-blue-400", bg: "bg-blue-500/10" },
    firebase: { slug: "firebase", color: "text-amber-400", bg: "bg-amber-500/10" },
    "firebase cloud messaging": { slug: "firebase", color: "text-amber-400", bg: "bg-amber-500/10" },
    fcm: { slug: "firebase", color: "text-amber-400", bg: "bg-amber-500/10" },
    aws: { slug: "amazonaws", color: "text-orange-400", bg: "bg-orange-500/10" },
    "aws ec2": { slug: "amazonec2", color: "text-orange-400", bg: "bg-orange-500/10" },
    "aws s3": { slug: "amazons3", color: "text-orange-400", bg: "bg-orange-500/10" },
    razorpay: { slug: "razorpay", color: "text-indigo-400", bg: "bg-indigo-500/10" },
    tailwind: { slug: "tailwindcss", color: "text-cyan-400", bg: "bg-cyan-500/10" },
    tailwindcss: { slug: "tailwindcss", color: "text-cyan-400", bg: "bg-cyan-500/10" },
    typescript: { slug: "typescript", color: "text-blue-500", bg: "bg-blue-500/10" },
    javascript: { slug: "javascript", color: "text-yellow-400", bg: "bg-yellow-500/10" },
    python: { slug: "python", color: "text-blue-400", bg: "bg-blue-500/10" },
    nextjs: { slug: "nextdotjs", color: "text-zinc-400", bg: "bg-zinc-500/10" },
    "next.js": { slug: "nextdotjs", color: "text-zinc-400", bg: "bg-zinc-500/10" },
    vue: { slug: "vuedotjs", color: "text-green-400", bg: "bg-green-500/10" },
    vuejs: { slug: "vuedotjs", color: "text-green-400", bg: "bg-green-500/10" },
    docker: { slug: "docker", color: "text-blue-400", bg: "bg-blue-500/10" },
    graphql: { slug: "graphql", color: "text-pink-400", bg: "bg-pink-500/10" },
    redis: { slug: "redis", color: "text-red-400", bg: "bg-red-500/10" },
    postgresql: { slug: "postgresql", color: "text-blue-400", bg: "bg-blue-500/10" },
    supabase: { slug: "supabase", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    vercel: { slug: "vercel", color: "text-zinc-400", bg: "bg-zinc-500/10" },
    prisma: { slug: "prisma", color: "text-zinc-200", bg: "bg-zinc-500/10" },
    nestjs: { slug: "nestjs", color: "text-red-500", bg: "bg-red-500/10" },
    kotlin: { slug: "kotlin", color: "text-orange-400", bg: "bg-orange-500/10" },
    swift: { slug: "swift", color: "text-orange-500", bg: "bg-orange-500/10" },
    vue3: { slug: "vuedotjs", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    svelte: { slug: "svelte", color: "text-orange-500", bg: "bg-orange-500/10" },
    astro: { slug: "astro", color: "text-amber-400", bg: "bg-amber-500/10" },
    bun: { slug: "bun", color: "text-zinc-200", bg: "bg-zinc-500/10" },
    deno: { slug: "deno", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    laravel: { slug: "laravel", color: "text-red-500", bg: "bg-red-500/10" },
    django: { slug: "django", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    spring: { slug: "spring", color: "text-emerald-500", bg: "bg-emerald-500/10" },
    "spring boot": { slug: "spring", color: "text-emerald-500", bg: "bg-emerald-500/10" },
    golang: { slug: "go", color: "text-cyan-500", bg: "bg-cyan-500/10" },
    go: { slug: "go", color: "text-cyan-500", bg: "bg-cyan-500/10" },
    rust: { slug: "rust", color: "text-orange-500", bg: "bg-orange-500/10" },
    java: { slug: "coffeescript", color: "text-orange-500", bg: "bg-orange-500/10" },
    "c#": { slug: "csharp", color: "text-indigo-400", bg: "bg-indigo-500/10" },
    dotnet: { slug: "dotnet", color: "text-indigo-400", bg: "bg-indigo-500/10" },
    "asp.net": { slug: "dotnet", color: "text-indigo-400", bg: "bg-indigo-500/10" },
    rediscloud: { slug: "redis", color: "text-red-400", bg: "bg-red-500/10" },
    kafka: { slug: "apachekafka", color: "text-orange-400", bg: "bg-orange-500/10" },
    rabbitmq: { slug: "rabbitmq", color: "text-orange-500", bg: "bg-orange-500/10" },
    nginx: { slug: "nginx", color: "text-emerald-500", bg: "bg-emerald-500/10" },
    git: { slug: "git", color: "text-orange-400", bg: "bg-orange-500/10" },
    github: { slug: "github", color: "text-zinc-400", bg: "bg-zinc-500/10" },
    figma: { slug: "figma", color: "text-purple-400", bg: "bg-purple-500/10" },
    otpless: { slug: null, color: "text-violet-400", bg: "bg-violet-500/10" },
    default: { slug: null, color: "text-muted-foreground", bg: "bg-muted/50" },
};

// Keywords used to infer tech stack from descriptions
export const TECH_KEYWORDS = [
    "Angular",
    "Ionic",
    "React",
    "Node.js",
    "Express",
    "MongoDB",
    "MySQL",
    "Firebase",
    "AWS",
];

// Status badge configuration for projects
export const PROJECT_STATUS_CONFIG = {
    "1": { label: "In Progress", color: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/20" },
    "2": { label: "Completed", color: "bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/20" },
    "3": { label: "On Hold", color: "bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20" },
};

// Gradient presets for bento cards
export const BENTO_GRADIENTS = [
    "from-violet-500/5 via-transparent to-transparent",
    "from-cyan-500/5 via-transparent to-transparent",
    "from-amber-500/5 via-transparent to-transparent",
    "from-emerald-500/5 via-transparent to-transparent",
    "from-rose-500/5 via-transparent to-transparent",
    "from-blue-500/5 via-transparent to-transparent",
];
