export const SUPPLEMENTAL_EVIDENCE = [{
    sourceImportId: "whatsapp-full-shailesh-nikita",
    type: "chat",
    title: "Complete WhatsApp conversation: Shailesh ↔ Nikita",
    category: "Chats / Messages",
    subcategory: "WhatsApp export",
    eventDate: "2023-11-16",
    eventTime: "14:03:34",
    description: "Complete WhatsApp text export containing 41,869 non-empty messages across 672 days, from 16 November 2023 through 30 August 2026.",
    peopleInvolved: ["Shailesh Sawale", "Nikita Ingle"],
    location: "",
    source: "WhatsApp export: _chat 2.txt",
    tags: ["WhatsApp", "Full export", "Chat"],
    notes: "The original UTF-8 text export is stored unchanged with the website. Messages are parsed locally in the browser for the chat-style viewer.",
    importance: "Normal",
    verificationStatus: "Unreviewed",
    platform: "WhatsApp",
    sender: "Shailesh",
    receiver: "Nikita Ingle",
    messageTimestamp: "2023-11-16T14:03:34",
    messageContent: "",
    messageCount: 41869,
    conversationEndDate: "2026-08-30",
    publicAttachmentPath: "/data/shailesh-nikita-whatsapp.txt",
    originalFilename: "shailesh-nikita-whatsapp.txt",
    fileType: "text/plain",
    relatedEvidenceIds: [],
}];
